### ISSUE TITLE
Please add energy_since_boot

### ISSUE THREAD

**Issue by cimnine** [home-assistant-ecosystem/python-mystrom#48]
It'd be great if you could add support for the `energy_since_boot` parameter from https://api.mystrom.ch/#fbb2c698-e37a-4584-9324-3f8b2f615fe2:

### Request
```
curl --location -g 'http://[switch_ip]/report'
```

### Response
```json
{
  "power": 240.67,
  "Ws": 226.89,
  "relay": true,
  "temperature": 25.72,
  "boot_id": "A425D9AD",
  "energy_since_boot": 299535913.95,
  "time_since_boot": 2234232
}
```

**Comment by slyoldfox** [comment]
@joostlek @fabaff to potentially fix https://github.com/home-assistant/core/issues/128572 at some point I added the newer energy fields. Hope you can manage to find some time to merge this and cut a release.

Thanks!
